import { Inter } from 'next/font/google'
import './globals.css'
import { Navigation } from '../components/navigation/navigation'
import { WhatsAppButton } from '@/components/whatsappButton/whatsappButton'
import { Footer } from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation></Navigation>
        {children}
        <WhatsAppButton></WhatsAppButton>
        <Footer></Footer>
      </body>
    </html>
  )
}
